github: itszzl-sudo
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective username
ko_fi: # Replace with your Ko-fi username
tidelift_platform: rust
tidelift_package_name: smart-text-editor
custom: # Replace with your custom sponsorship URL
